name: Readme Generator

on:
  schedule:
    - cron: '0 */12 * * *' # every 12 hours
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v1
        with:
          token: ${{ secrets.USER_TOKEN }}
          template: ./Template.md
          readme: ./Readme.md
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config user.name Github Actions
          git add .
          git commit -m "Update README"
          git push
          fi
