name: Readme Generator

on:
  schedule:
    - cron: '0 0 */1 * *' # every Day at 00:00 UTC
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate README.md
        uses: teoxoy/profile-readme-stats@v2
        with:
          token: ${{ secrets.USER_TOKEN }}
          template: ./Template.md
          readme: ./Readme.md
      - name: Update README.md
        run: |
          if [[ "$(git status --porcelain)" != "" ]]; then
          git config --global user.name "Github Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update README"
          git push
          fi
